name: ehelp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  awesome_dialog: ^3.0.2
  calendar_date_picker2: ^0.3.5
  cool_alert: ^2.0.1
  cupertino_icons: ^1.0.2
  custom_timer: ^0.2.3
  dropdown_button2: ^1.9.2
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_credit_card: ^3.0.4
  flutter_localizations:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_mobx: ^2.0.6+5
  flutter_native_splash:
  flutter_svg: ^2.0.5
  flutter_rating_bar: ^4.0.1
  get_it: ^7.2.0
  http: ^0.13.6
  image_picker: ^0.8.6+1
  lottie: ^2.1.0
  mobx: ^2.1.3
  mobx_codegen: ^2.1.1
  shifting_tabbar: ^1.0.2
  salomon_bottom_bar: ^3.3.1
  shared_preferences: ^2.1.1
  syncfusion_flutter_sliders: ^20.4.50
  carousel_slider: ^4.2.1
  transparent_image: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#0d0d0d"
  branding: "assets/images/splash-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
    - family: Lexend
      fonts:
        - asset: assets/fonts/lexend/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/lexend/Lexend-Regular.ttf
        - asset: assets/fonts/lexend/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/lexend/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/lexend/Lexend-Black.ttf
          weight: 900
         

